version: '3'
networks:
  default:
    external:
      name: pnu
services:
  client.pusan.ac.kr:
    restart: always
    container_name: client.pusan.ac.kr
    image: maked_node:14.17
    working_dir: /usr/app
    command: npm start
    volumes:
      - ../build/crypto-config:~~~